version: '2'
services:
  nginx:
    build: containers/nginx
    ports:
      - '8080:80'
    links:
      - app
    volumes:
      - ./public:/usr/src/Blog/public
  mysql:
    image: mysql:5.7.10
    environment:
      MYSQL_ROOT_PASSWORD: 'otyanomitaiyo1123'
    ports:
      - '3321:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  elasticsearch:
    build: containers/elasticsearch-himanoa
    ports:
      - '9200:9200'
      - '9300:9300'
  app:
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/Blog
    links:
      - mysql
      - elasticsearch
volumes:
  mysql-data:
    driver: local
